[28-Sep-2025 08:38:43 UTC] PHP Fatal error:  Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'http_response_c...', Array)
#3 [internal function]: App\Core\ExceptionHandler::handle(Object(ErrorException))
#4 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php on line 98
[28-Sep-2025 08:38:43 UTC] PHP Fatal error:  Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'Uncaught ErrorE...', Array)
#3 /var/www/html/api/core/ExceptionHandler.php(121): App\Core\ExceptionHandler::handle(Object(ErrorException))
#4 [internal function]: App\Core\ExceptionHandler::handleShutdown()
#5 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php on line 98
[28-Sep-2025 08:38:57 UTC] PHP Fatal error:  Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'http_response_c...', Array)
#3 [internal function]: App\Core\ExceptionHandler::handle(Object(ErrorException))
#4 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php on line 98
[28-Sep-2025 08:38:57 UTC] PHP Fatal error:  Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'Uncaught ErrorE...', Array)
#3 /var/www/html/api/core/ExceptionHandler.php(121): App\Core\ExceptionHandler::handle(Object(ErrorException))
#4 [internal function]: App\Core\ExceptionHandler::handleShutdown()
#5 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php on line 98
[28-Sep-2025 08:40:31 UTC] PHP Fatal error:  Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'http_response_c...', Array)
#3 [internal function]: App\Core\ExceptionHandler::handle(Object(ErrorException))
#4 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php on line 98
[28-Sep-2025 08:40:31 UTC] PHP Fatal error:  Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'Uncaught ErrorE...', Array)
#3 /var/www/html/api/core/ExceptionHandler.php(121): App\Core\ExceptionHandler::handle(Object(ErrorException))
#4 [internal function]: App\Core\ExceptionHandler::handleShutdown()
#5 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php on line 98
[28-Sep-2025 08:45:41 UTC] PHP Fatal error:  Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'Call to undefin...', Array)
#3 [internal function]: App\Core\ExceptionHandler::handle(Object(Error))
#4 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php on line 98
[28-Sep-2025 08:45:41 UTC] PHP Fatal error:  Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'Uncaught ErrorE...', Array)
#3 /var/www/html/api/core/ExceptionHandler.php(121): App\Core\ExceptionHandler::handle(Object(ErrorException))
#4 [internal function]: App\Core\ExceptionHandler::handleShutdown()
#5 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php on line 98
